[workspace]
members = [
  "crates/node",
  "crates/json-rpc",
  "crates/subscriber",
  "crates/types",
]
resolver = "2"

[workspace.dependencies]
mohave-chain-json-rpc = { path = "crates/json-rpc" }
mohave-chain-node = { path = "crates/node" }
mohave-chain-types = { path = "crates/types" }

futures = "0.3"
serde = { version = "1", default-features = false }
thiserror = "2"
tokio = { version = "1", default-features = false }
tokio-stream = "0.1"
toml = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
trait-variant = "0.1"
clap = { version = "4.5", features = ["derive"] }
